# Generated by Django 5.2.5 on 2025-09-03 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_snippet_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='status',
            field=models.BooleanField(choices=[(False, 'Public'), (True, 'Private')], default=False),
        ),
    ]
